server:
  port: 8080

## 47.96.70.159 huihui 123456
spring:
  data:
    mongodb:
      uri: mongodb://47.96.70.159:27017/huihui
      #uri: mongodb://mytest:mytest@mongo1:30002,mongo2:30002,mongo3:30002/pzb_app_phone?replicaSet=replSet&readPreference=secondaryPreferred&connectTimeoutMS=300000
      #uri: mongodb://mytest:mytest@192.168.0.4:30002,192.168.0.6:30002,10.80.220.46:30002/mytest
      #uri: mongodb://mytest:mytest@192.168.1.241:27017,192.168.1.123:27017,192.168.1.200:27017/mytest
      option:
        min-connection-per-host: 5
        max-connection-per-host: 100
        threads-allowed-to-block-for-connection-multiplier: 20
        server-selection-timeout: 30000
        max-wait-time: 120000
        max-connection-idle-time: 0
        max-connection-life-time: 0
        connect-timeout: 10000
        socket-timeout: 0
        socket-keep-alive: false
        ssl-enabled: false
        ssl-invalid-host-name-allowed: false
        always-use-m-beans: false
        heartbeat-socket-timeout: 20000
        heartbeat-connect-timeout: 20000
        min-heartbeat-frequency: 500
        heartbeat-frequency: 10000
        local-threshold: 15
      authentication-database: admin
  datasource:
    name: test
    url: jdbc:mysql://47.96.70.159:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: huihui
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    druid:
      driver-class-name:

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.it.huihui.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  path: '/Users/jackie/workspace/rome/'
  file: 'springboot.log'
  pattern:
    console: '%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n'
    file: '%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n'
  # 打印sql语句
  level:
    com.banner.boke.web.mapper : debug


